<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <WarningLevel>9999</WarningLevel>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <WarningLevel>9999</WarningLevel>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.11.1" />
        <PackageReference Include="Tesseract" Version="5.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\DocumentsModel\DocumentsModel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="tessdata\1830PalmyraEdition.traineddata">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="tessdata\eng.traineddata">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
